/**
 * Created by pioneerroad on 31/08/15.
 */

module.exports = {

        friendsNearby: 'SELECT "relationship_friends"."userA" AS friend, "user_profiles"."nickName" AS nickname, "dataSet_towns"."location", "dataSet_towns"."tourism_region", "dataSet_towns"."state", ST_Distance_Sphere((SELECT "user_profiles"."the_geom" FROM "user_profiles" WHERE "user_profiles"."userAccountId" = :uid), "user_profiles"."the_geom") / 1000 as distance FROM "relationship_friends" LEFT JOIN "user_profiles" ON "relationship_friends"."userA" = "user_profiles"."userAccountId" LEFT JOIN "dataSet_towns" ON "dataSet_towns"."id" = "user_profiles"."homeTownId" WHERE "relationship_friends"."userB" = :uid UNION SELECT "relationship_friends"."userB" AS friend, "user_profiles"."nickName" AS nickname, "dataSet_towns"."location", "dataSet_towns"."tourism_region", "dataSet_towns"."state", ST_Distance_Sphere((SELECT "user_profiles"."the_geom" FROM "user_profiles" WHERE "user_profiles"."userAccountId" = :uid), "user_profiles"."the_geom") / 1000 AS distance FROM "relationship_friends" LEFT JOIN "user_profiles" ON "relationship_friends"."userB" = "user_profiles"."userAccountId" LEFT JOIN "dataSet_towns" ON "dataSet_towns"."id" = "user_profiles"."homeTownId" WHERE "relationship_friends"."userA" = :uid AND "relationship_friends"."status" = \'active\';',
        pendingFriendRequests: 'SELECT "user_profiles"."userAccountId", "user_profiles"."nickName", "user_profiles"."profilePhoto", "dataSet_towns"."location", "dataSet_towns"."state", "dataSet_towns"."tourism_region" FROM "relationship_friends" LEFT JOIN "user_profiles" ON "relationship_friends"."initiator" = "user_profiles"."userAccountId" LEFT JOIN "dataSet_towns" ON "dataSet_towns"."id" = "user_profiles"."homeTownId" WHERE "relationship_friends"."recipient" = :uid AND "relationship_friends"."status" = \'pending\'',
        activeFriends: 'SELECT "relationship_friends"."userA" AS friend, "user_profiles"."nickName" AS nickname, "user_profiles"."profilePhoto", "user_profiles"."homeTownId", "dataSet_towns"."location", "dataSet_towns"."state", "dataSet_towns"."tourism_region" FROM "relationship_friends" LEFT JOIN "user_profiles" ON "relationship_friends"."userA" = "user_profiles"."userAccountId" LEFT JOIN "dataSet_towns" ON "user_profiles"."homeTownId" = "dataSet_towns"."id" WHERE "relationship_friends"."userB" = :uid UNION SELECT "relationship_friends"."userB" AS friend, "user_profiles"."nickName" AS nickname, "user_profiles"."profilePhoto", "user_profiles"."homeTownId", "dataSet_towns"."location", "dataSet_towns"."state", "dataSet_towns"."tourism_region" FROM "relationship_friends" LEFT JOIN "user_profiles" ON "relationship_friends"."userB" = "user_profiles"."userAccountId" LEFT JOIN "dataSet_towns" ON "user_profiles"."homeTownId" = "dataSet_towns"."id" WHERE "relationship_friends"."userA" = :uid AND "relationship_friends"."status" = \'active\''
};